site_name: Islamey
site_author: Islam Mohamed
site_description: About Islamey Application .
copyright: Copyright &copy; 2024 Islam Mohamed
repo_url: https://github.com/IslamMohammedSalama/Islamey.git
theme:
  name: material
  logo: /assets/icon.png
  favicon: /assets/icon.png
  features:
    - content.code.copy
    - content.code.highlight
    - content.code.select
    - content.code.annotate
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - announce.dismiss
    - navigation.footer
plugins:
  - search
  - tags
