name: islamey
description: "مشروع اسلامي جديد !"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:

  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  syncfusion_flutter_pdfviewer: ^25.1.35
  flutter_native_splash: ^2.3.13
  http: ^1.2.1
  flutter_settings_ui: ^3.0.1
  provider: ^6.1.2
  hexcolor: ^3.0.1
  rename: ^3.0.2
  flutter_colorpicker: ^1.0.3
  get: ^4.6.6
  circular_countdown_timer: ^0.2.3
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.3
  share_plus: ^9.0.0
  url_launcher: ^6.1.6
  scrollable_positioned_list: ^0.3.8
  intl: ^0.19.0
  flutter_local_notifications: ^17.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints : ^3.0.1
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/icons/icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"

flutter_native_splash:
  color: "#000000"
  image: assets/images/splash.jpeg
  android_gravity: fill
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/files/
    - assets/fonts/
    - assets/audio/
    - assets/icons/
    - assets/pdf/
    - assets/json/

  fonts:
    - family: IBMPlexSansArabic-Thin
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Thin.ttf
    - family: aBMPlexSansArabic-Bold
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Bold.ttf
    - family:  digital-mono
      fonts:
        - asset: assets/fonts/digital-mono.ttf
    - family:  digital-italic-bold
      fonts:
        - asset: assets/fonts/digital-italic-bold.ttf
    - family:  digital-italic
      fonts:
        - asset: assets/fonts/digital-italic.ttf
    - family:  digital-normel
      fonts:
        - asset: assets/fonts/digital-normel.ttf
    - family: quran
      fonts:
        - asset: assets/fonts/HafsSmart_08.ttf
    - family: me_quran
      fonts:
        - asset: assets/fonts/me_quran.ttf
